# Homework 1

In [1]:
import numpy as np

np.random.seed(42)
np.set_printoptions(suppress=True)

In [2]:
# Task 1. Create a 1-dimensional array (vector) with first 10 natural integers
vector = np.arange(1, 11)

print(f"Vector:\n{vector}")
print(f"Number of dimensions: {vector.ndim}")

Vector:
[ 1  2  3  4  5  6  7  8  9 10]
Number of dimensions: 1


In [3]:
# Task 2. Create a 2-dimensional array (a 3x3 matrix) filled with zeros
matrix = np.zeros((3, 3), dtype=np.int8)

print(f"Matrix:\n{matrix}")
print(f"Number of dimensions: {matrix.ndim}")

Matrix:
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Number of dimensions: 2


In [4]:
# Task 3. Create a 5x5 matrix and fill it with random whole numbers (from 1 to 10)
matrix = np.random.randint(1, 11, size=(5, 5))

print(f"Matrix:\n{matrix}")
print(f"Number of dimensions: {matrix.ndim}")

Matrix:
[[ 7  4  8  5  7]
 [10  3  7  8  5]
 [ 4  8  8  3  6]
 [ 5  2  8  6  2]
 [ 5  1 10  6  9]]
Number of dimensions: 2


In [5]:
# Task 4. Create a 4x4 matrix and fill it with random numbers (from 0 to 1)
matrix = np.random.rand(4, 4)

print(f"Matrix:\n{matrix}")
print(f"Number of dimensions: {matrix.ndim}")

Matrix:
[[0.29122914 0.61185289 0.13949386 0.29214465]
 [0.36636184 0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041 0.60754485]
 [0.17052412 0.06505159 0.94888554 0.96563203]]
Number of dimensions: 2


In [6]:
# Task 5. Create 2 vectors of size 5, fill them with random integers from 1 to 10, and perform addition, subtraction, and multiplication
vector_1 = np.random.randint(1, 11, 5)
vector_2 = np.random.randint(1, 11, 5)

print(f"Addition:\n{vector_1 + vector_2}\n")
print(f"Subtraction:\n{vector_1 - vector_2}\n")
print(f"Multiplication:\n{vector_1 * vector_2}")

Addition:
[ 4 14 16 18  8]

Subtraction:
[0 6 2 2 2]

Multiplication:
[ 4 40 63 80 15]


In [7]:
# Task 6. Create 2 vectors of size 7, fill them with random integers, and calculate the dot product
vector_1, vector_2 = np.random.randint(1, 11, 5), np.random.randint(10, 21, 5)

print(f"Dot product:\n{np.dot(vector_2, vector_2)}")

Dot product:
1101


In [8]:
# Task 7. Create 2 matrices of size 2x2 and 2x3, fill them with random whole numbers, and multiply them 
matrix_1, matrix_2 = np.random.randint(1, 11, size=(2, 2)), np.random.randint(20, 21, size=(2, 3))

print(f"Dot product:\n{np.dot(matrix_1, matrix_2)}")

Dot product:
[[160 160 160]
 [240 240 240]]


In [9]:
# Task 8. Create a 3x3 matrix, fill it with random whole numbers from 1 to 10, and calculate its inverted value
matrix = np.random.randint(1, 11, size=(3, 3))
matrix_inverted = np.linalg.inv(matrix)

print(f"Inverted matrix:\n{matrix_inverted}")

Inverted matrix:
[[ 0.46774194 -0.06451613 -0.64516129]
 [ 0.08064516  0.16129032 -0.38709677]
 [-0.5         0.          1.        ]]


In [10]:
# Task 9. Create a 4x4 matrix, fill it with random real numbers from 0 to 1, and transpose it
matrix = np.random.rand(4, 4).T

print(f"Matrix transposed:\n{matrix}")

Matrix transposed:
[[0.58675117 0.29627351 0.39488152 0.71134195]
 [0.96525531 0.16526694 0.29348817 0.79017554]
 [0.60703425 0.01563641 0.01407982 0.60595997]
 [0.27599918 0.42340148 0.1988424  0.92630088]]


In [11]:
# Task 10. Create a 3x4 matrix and a vector of the size of 4, fill them with random whole numbers from 1 to 10, and multiply the matrix by the vector 
matrix, vector = np.random.randint(1, 11, size=(3, 4)), np.random.randint(1, 11, 4)

print(f"Matrix 3x4:\n{matrix}\n")
print(f"Vector:\n{vector}\n")
print(f"Matrix * Vector:\n{matrix * vector}")

Matrix 3x4:
[[10  9  7  9]
 [ 8  2  1  7]
 [ 7  8  5  3]]

Vector:
[8 6 3 1]

Matrix * Vector:
[[80 54 21  9]
 [64 12  3  7]
 [56 48 15  3]]


In [12]:
# Task 11. Create a 2x3 matrix and a vector of the size of 3, fill them with random numbers from 0 to 1, and multiply the matrix by the vector
matrix, vector = np.random.rand(2, 3), np.random.rand(3)

print(f"Matrix * Vector:\n{matrix * vector}")

Matrix * Vector:
[[0.01548311 0.69055973 0.09413675]
 [0.02918212 0.16770572 0.02839563]]


In [13]:
# Task 12. Create two 2x2 matrices, fill them with random integers from 1 to 10, and perform matrix multiplication by element
matrix_1, matrix_2 = np.random.randint(1, 11, size=(2, 2)), np.random.randint(1, 11, size=(2, 2))

print(f"Matrix 1:\n{matrix_1}\n")
print(f"Matrix 2:\n{matrix_2}\n")
print(f"Matrix 1 * Matrix 2:\n{matrix_1 * matrix_2}")

Matrix 1:
[[3 7]
 [1 4]]

Matrix 2:
[[4 5]
 [7 7]]

Matrix 1 * Matrix 2:
[[12 35]
 [ 7 28]]


In [14]:
# Task 13. Create two 2x2 matrices, fill them with random integers from 1 to 10, and calculate their dot product
matrix_1, matrix_2 = np.random.randint(1, 11, size=(2, 2)), np.random.randint(1, 11, size=(2, 2))

print(f"Matrix 1:\n{matrix_1}\n")
print(f"Matrix 2:\n{matrix_2}\n")
print(f"Matrix 1 * Matrix 2 dot product:\n{np.dot(matrix_1, matrix_2)}")

Matrix 1:
[[4 7]
 [3 6]]

Matrix 2:
[[ 2 10]
 [ 9  5]]

Matrix 1 * Matrix 2 dot product:
[[71 75]
 [60 60]]


In [15]:
# Task 14. Create a 5x5 matrix, fill it with random integers from 1 to 100, and calculate the sum of all the matrix elements
matrix = np.random.randint(1, 101, size=(5, 5))

print(f"Matrix:\n{matrix}\n")
print(f"The sum of all the matrix elements: {np.sum(matrix)}")

Matrix:
[[ 6 28 28 44 84]
 [30 62 75 92 89]
 [62 97  1 27 62]
 [77  3 70 72 27]
 [ 9 62 37 97 51]]

The sum of all the matrix elements: 1292


In [16]:
# Task 15. Create two 4x4 matrices, fill them with random numbers from 0 to 10, and calculate their difference
matrix_1, matrix_2 = np.random.randint(1, 11, size=(4, 4)), np.random.randint(1, 11, size=(4, 4))

print(f"Matrix 1:\n{matrix_1}\n")
print(f"Matrix 2:\n{matrix_2}\n")
print(f"Matrix 1 and Matrix 2 subtraction difference:\n{matrix_1 - matrix_2}")

Matrix 1:
[[10  8  6  8]
 [ 9  4  1  1]
 [10  4  7  2]
 [ 3  1  5  1]]

Matrix 2:
[[ 8  1  1  2]
 [ 2  6  7  5]
 [ 1  1  3  2]
 [ 5 10  6  7]]

Matrix 1 and Matrix 2 subtraction difference:
[[ 2  7  5  6]
 [ 7 -2 -6 -4]
 [ 9  3  4  0]
 [-2 -9 -1 -6]]


In [17]:
# Task 16. Create a 3x3 matrix, fill it with random numbers from 0 to 1, and allocate a column vector that contains the sum of all the elements in a matrix row
matrix = np.random.rand(3, 3)
sum_column = np.sum(matrix, axis=1).reshape(-1, 1)

print(f"Matrix:\n{matrix}\n")
print(f"Sum column:\n{sum_column}")

Matrix:
[[0.67213555 0.76161962 0.23763754]
 [0.72821635 0.36778313 0.63230583]
 [0.63352971 0.53577468 0.09028977]]

Sum column:
[[1.67139271]
 [1.72830531]
 [1.25959416]]


In [18]:
# Task 17. Create a 3x4 matrix, fill it with random integers, and define a new matrix that contains the square values of matrix_1 elements
matrix = np.random.randint(1, 101, size=(3, 4))
matrix_square = np.square(matrix)

print(f"Matrix:\n{matrix}\n")
print(f"Square values matrix:\n{matrix_square}")

Matrix:
[[97 73 59 70]
 [80 93  3 20]
 [59 36 19 90]]

Square values matrix:
[[9409 5329 3481 4900]
 [6400 8649    9  400]
 [3481 1296  361 8100]]


In [19]:
# Task 18. Create a vector of the size of 4, fill it with random integers from 1 to 50, and define a new vector that contains square root values of vector_1
vector = np.random.randint(1, 51, size=(4,))
vector_square_root = np.sqrt(vector)

print(f"Vector:\n{vector}\n")
print(f"Square root vector:\n{vector_square_root}")

Vector:
[ 3 19 20 32]

Square root vector:
[1.73205081 4.35889894 4.47213595 5.65685425]
