# Homework 1

In [70]:
import numpy as np

np.random.seed(42)

In [71]:
# Task 1
vector_1 = np.arange(1, 11)
print(vector_1)
print(f"Number of dimensions: {vector_1.ndim}")

[ 1  2  3  4  5  6  7  8  9 10]
Number of dimensions: 1


In [72]:
# Task 2
matrix_1 = np.zeros(9).reshape((3, 3))
print(matrix_1)
print(f"Number of dimensions: {matrix_1.ndim}")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Number of dimensions: 2


In [73]:
# Task 3
matrix_2 = np.random.randint(1, 11, 25).reshape((5, 5))
print(matrix_2)
print(f"Number of dimensions: {matrix_2.ndim}")

[[ 7  4  8  5  7]
 [10  3  7  8  5]
 [ 4  8  8  3  6]
 [ 5  2  8  6  2]
 [ 5  1 10  6  9]]
Number of dimensions: 2


In [74]:
# Task 4
matrix_3 = np.array([np.random.uniform(0, 1) for i in range(16)]).reshape((4, 4))
print(matrix_3)
print(f"Number of dimensions: {matrix_3.ndim}")

[[0.29122914 0.61185289 0.13949386 0.29214465]
 [0.36636184 0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041 0.60754485]
 [0.17052412 0.06505159 0.94888554 0.96563203]]
Number of dimensions: 2


In [79]:
# Task 5
vector_2 = np.random.randint(1, 11, 5)
vector_3 = np.random.randint(1, 11, 5)
print(f"Addition: {vector_2 + vector_3}")
print(f"Subtraction: {vector_2 - vector_3}")
print(f"Multiplication: {vector_2 * vector_3}")

Addition: [ 9 10 12 17 18]
Subtraction: [-1  6  2  1 -2]
Multiplication: [20 16 35 72 80]


In [80]:
# Task 6
vector_4, vector_5 = np.random.randint(1, 11, 5), np.random.uniform(0, 1, 5)
print(f"Dot product: {np.dot(vector_4, vector_5)}")

Dot product: 9.176650397712887


In [84]:
# Task 7
matrix_4, matrix_5 = np.random.randint(1, 11, 4).reshape((2, 2)), np.random.randint(1, 11, 6).reshape((2, 3))
print(f"Dot product: {np.dot(matrix_4, matrix_5)}")

Dot product: [[ 57  85  52]
 [ 70 110  60]]


In [ ]:
# Task 8
