# Homework 1

In [1]:
import numpy as np

np.random.seed(42)
np.set_printoptions(suppress=True)

In [2]:
# Task 1
vector_1 = np.arange(1, 11)

print(f"Vector:\n{vector_1}")
print(f"Number of dimensions: {vector_1.ndim}")

Vector:
[ 1  2  3  4  5  6  7  8  9 10]
Number of dimensions: 1


In [3]:
# Task 2
matrix_1 = np.zeros(9).reshape((3, 3))

print(f"Matrix:\n{matrix_1}")
print(f"Number of dimensions: {matrix_1.ndim}")

Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Number of dimensions: 2


In [4]:
# Task 3
matrix_2 = np.random.randint(1, 11, 25).reshape((5, 5))

print(f"Matrix:\n{matrix_2}")
print(f"Number of dimensions: {matrix_2.ndim}")

Matrix:
[[ 7  4  8  5  7]
 [10  3  7  8  5]
 [ 4  8  8  3  6]
 [ 5  2  8  6  2]
 [ 5  1 10  6  9]]
Number of dimensions: 2


In [5]:
# Task 4
matrix_3 = np.array([np.random.uniform(0, 1) for i in range(16)]).reshape((4, 4))

print(f"Matrix:\n{matrix_3}")
print(f"Number of dimensions: {matrix_3.ndim}")

Matrix:
[[0.29122914 0.61185289 0.13949386 0.29214465]
 [0.36636184 0.45606998 0.78517596 0.19967378]
 [0.51423444 0.59241457 0.04645041 0.60754485]
 [0.17052412 0.06505159 0.94888554 0.96563203]]
Number of dimensions: 2


In [6]:
# Task 5
vector_2 = np.random.randint(1, 11, 5)
vector_3 = np.random.randint(1, 11, 5)

print(f"Addition:\n{vector_2 + vector_3}\n")
print(f"Subtraction:\n{vector_2 - vector_3}\n")
print(f"Multiplication:\n{vector_2 * vector_3}")

Addition:
[ 4 14 16 18  8]

Subtraction:
[0 6 2 2 2]

Multiplication:
[ 4 40 63 80 15]


In [7]:
# Task 6
vector_4, vector_5 = np.random.randint(1, 11, 5), np.random.uniform(0, 1, 5)

print(f"Dot product:\n{np.dot(vector_4, vector_5)}")

Dot product:
8.842577874749665


In [8]:
# Task 7
matrix_4, matrix_5 = np.random.randint(1, 11, 4).reshape((2, 2)), np.random.randint(1, 11, 6).reshape((2, 3))

print(f"Dot product:\n{np.dot(matrix_4, matrix_5)}")

Dot product:
[[ 96  80  94]
 [112  90  98]]


In [9]:
# Task 8
matrix_6 = np.random.randint(1, 11, 9).reshape((3, 3))
matrix_inverted = np.linalg.inv(matrix_6)

print(f"Matrix inverted:\n{matrix_inverted}")

Matrix inverted:
[[-0.19170984  0.00518135  0.21243523]
 [ 0.1865285   0.11658031 -0.22020725]
 [ 0.04663212 -0.09585492  0.06994819]]


In [10]:
# Task 9
matrix_7 = np.random.uniform(0, 1, 16).reshape((4, 4)).T

print(f"Matrix transposed:\n{matrix_7}")

Matrix transposed:
[[0.77224477 0.70685734 0.35846573 0.33089802]
 [0.19871568 0.72900717 0.11586906 0.06355835]
 [0.00552212 0.77127035 0.86310343 0.31098232]
 [0.81546143 0.07404465 0.62329813 0.32518332]]


In [11]:
# Task 10
matrix_8, vector_6 = np.random.randint(1, 11, 12).reshape((3, 4)), np.random.randint(1, 11, 4)

print(f"Matrix 3x4:\n{matrix_8}\n")
print(f"Vector:\n{vector_6}\n")
print(f"Matrix * Vector:\n{matrix_8 * vector_6}")

Matrix 3x4:
[[ 3  8  6  3]
 [ 1  3  5  3]
 [ 1  5 10  7]]

Vector:
[ 7  9 10 10]

Matrix * Vector:
[[ 21  72  60  30]
 [  7  27  50  30]
 [  7  45 100  70]]


In [12]:
# Task 11
matrix_9, vector_7 = np.random.uniform(0, 1, 6).reshape((2, 3)), np.random.uniform(0, 1, 3)

print(f"Matrix * Vector:\n{matrix_9 * vector_7}")

Matrix * Vector:
[[0.06121339 0.12192259 0.48357   ]
 [0.06623402 0.34045355 0.37546816]]


In [13]:
# Task 12
matrix_10, matrix_11 = np.random.randint(1, 11, 4).reshape((2, 2)), np.random.randint(1, 11, 4).reshape((2, 2))

print(f"Matrix 1:\n{matrix_10}\n")
print(f"Matrix 2:\n{matrix_11}\n")
print(f"Matrix 1 * Matrix 2:\n{matrix_10 * matrix_11}")

Matrix 1:
[[4 7]
 [3 6]]

Matrix 2:
[[ 2 10]
 [ 9  5]]

Matrix 1 * Matrix 2:
[[ 8 70]
 [27 30]]


In [14]:
# Task 13
matrix_12, matrix_13 = np.random.randint(1, 11, 4).reshape((2, 2)), np.random.randint(1, 11, 4).reshape((2, 2))

print(f"Matrix 1:\n{matrix_12}\n")
print(f"Matrix 2:\n{matrix_13}\n")
print(f"Matrix 1 * Matrix 2 dot product:\n{np.dot(matrix_12, matrix_13)}")

Matrix 1:
[[ 6  4]
 [10  7]]

Matrix 2:
[[9 7]
 [1 1]]

Matrix 1 * Matrix 2 dot product:
[[58 46]
 [97 77]]


In [15]:
# Task 14
matrix_14 = np.random.randint(1, 101, 25).reshape((5, 5))

print(f"Matrix:\n{matrix_14}\n")
print(f"The sum of all the matrix elements: {np.sum(matrix_14)}")

Matrix:
[[27 62 77  3 70]
 [72 27  9 62 37]
 [97 51 44 24 79]
 [59 32 96 88 52]
 [62 58 52 12 39]]

The sum of all the matrix elements: 1291


In [35]:
# Task 15
matrix_15, matrix_16 = np.random.randint(1, 11, 16).reshape((4, 4)), np.random.randint(1, 11, 16).reshape((4, 4))

print(f"Matrix 1:\n{matrix_15}\n")
print(f"Matrix 2:\n{matrix_16}\n")
print(f"Matrix 1 and Matrix 2 subtraction difference:\n{matrix_15 - matrix_16}")

Matrix 1:
[[ 5  8 10  4]
 [10  8 10  2]
 [ 5  9  4  6]
 [ 1  9  1  5]]

Matrix 2:
[[ 4  3  6  2]
 [ 3  5  9  2]
 [10  8  2  5]
 [ 7  8  1  6]]

Matrix 1 and Matrix 2 subtraction difference:
[[ 1  5  4  2]
 [ 7  3  1  0]
 [-5  1  2  1]
 [-6  1  0 -1]]


In [22]:
# Task 16
matrix_17 = np.random.uniform(0, 1, 9).reshape((3, 3))

print(f"Matrix:\n{matrix_17}")

Matrix:
[[0.51209306 0.22649578 0.64517279]
 [0.17436643 0.69093774 0.38673535]
 [0.93672999 0.13752094 0.34106635]]
